unipayment_configuration_form:
  path: /unipayment/configuration_form
  methods: [GET, POST]
  defaults:
    _controller: 'prestashop.module.unipayment.controller.unipayment_configuration::index'

unipayment_kop_mapping_save:
  path: /unipayment/kop/save
  methods: [POST]
  defaults:
    _controller: 'prestashop.module.unipayment.controller.unipayment_configuration::saveKopMapping'

unipayment_kop_mapping_refresh:
  path: /unipayment/kop/refresh
  methods: [POST]
  defaults:
    _controller: 'prestashop.module.unipayment.controller.unipayment_configuration::refreshKopMapping'
